import { avatar, hashPassword, nowIso, privateConversationId } from "../shared/utils.js";

function messageSeed(id, conversationType, conversationId, senderId, content, minutesAgo) {
  return {
    id,
    conversationType,
    conversationId,
    senderId,
    content,
    messageType: "text",
    status: "sent",
    deliveredTo: [],
    readBy: [senderId],
    createdAt: new Date(Date.now() + minutesAgo * 60 * 1000).toISOString(),
  };
}

export const demoUsers = [
  {
    id: "u_linche",
    username: "linche",
    email: "linche@flowlink.local",
    displayName: "林澈",
    role: "前端体验设计",
    department: "体验组",
    phone: "138-0000-2601",
    location: "武汉",
    statusMessage: "正在打磨 FlowLink 的聊天体验。",
    bio: "负责微信风格 UI、个人资料页和消息交互。",
    color: "#07c160",
    salt: "flowlink-linche",
  },
  {
    id: "u_shenyan",
    username: "shenyan",
    email: "shenyan@flowlink.local",
    displayName: "沈砚",
    role: "通信架构师",
    department: "后端组",
    phone: "138-0000-2602",
    location: "武汉",
    statusMessage: "关注长连接、ACK 与消息路由。",
    bio: "负责整体通信架构和实时链路。",
    color: "#2f80ed",
    salt: "flowlink-shenyan",
  },
  {
    id: "u_xuzhihang",
    username: "xuzhihang",
    email: "xuzhihang@flowlink.local",
    displayName: "许知航",
    role: "WebSocket 客户端",
    department: "前端组",
    phone: "138-0000-2603",
    location: "杭州",
    statusMessage: "把消息状态机做稳。",
    bio: "负责实时状态管理、文件消息和消息幂等。",
    color: "#7c3aed",
    salt: "flowlink-xuzhihang",
  },
  {
    id: "u_zhouyu",
    username: "zhouyu",
    email: "zhouyu@flowlink.local",
    displayName: "周屿",
    role: "安全与缓存",
    department: "平台组",
    phone: "138-0000-2604",
    location: "南京",
    statusMessage: "先把安全边界画清楚。",
    bio: "负责 JWT、Redis 网关、敏感词和禁言策略。",
    color: "#f97316",
    salt: "flowlink-zhouyu",
  },
  {
    id: "u_yelan",
    username: "yelan",
    email: "yelan@flowlink.local",
    displayName: "叶岚",
    role: "数据负责人",
    department: "数据组",
    phone: "138-0000-2605",
    location: "上海",
    statusMessage: "表结构已经就绪。",
    bio: "负责 MySQL、文件记录和数据映射。",
    color: "#0f766e",
    salt: "flowlink-yelan",
  },
  {
    id: "u_songyao",
    username: "songyao",
    email: "songyao@flowlink.local",
    displayName: "宋遥",
    role: "后端业务开发",
    department: "业务组",
    phone: "138-0000-2606",
    location: "成都",
    statusMessage: "补齐好友和群组闭环。",
    bio: "负责用户、好友、群组和通知业务。",
    color: "#e11d48",
    salt: "flowlink-songyao",
  },
];

function buildUser(user, demoPassword, createdAt) {
  return {
    id: user.id,
    username: user.username,
    email: user.email,
    displayName: user.displayName,
    role: user.role,
    department: user.department,
    phone: user.phone,
    location: user.location,
    statusMessage: user.statusMessage,
    bio: user.bio,
    avatar: avatar(user.displayName, user.color),
    password: hashPassword(demoPassword, user.salt),
    status: "offline",
    createdAt,
  };
}

export function seedDb() {
  const demoPassword = "flowlink123";
  const createdAt = nowIso();
  const users = demoUsers.map((user) => buildUser(user, demoPassword, createdAt));

  return {
    users,
    sessions: {},
    friendships: [
      { id: "fr_1", users: ["u_linche", "u_shenyan"], createdAt },
      { id: "fr_2", users: ["u_linche", "u_xuzhihang"], createdAt },
      { id: "fr_3", users: ["u_linche", "u_zhouyu"], createdAt },
      { id: "fr_4", users: ["u_shenyan", "u_xuzhihang"], createdAt },
      { id: "fr_5", users: ["u_shenyan", "u_yelan"], createdAt },
      { id: "fr_6", users: ["u_zhouyu", "u_songyao"], createdAt },
    ],
    friendRequests: [
      {
        id: "req_1",
        fromId: "u_yelan",
        toId: "u_linche",
        status: "pending",
        message: "数据库结构已经准备好，拉我进前端联调。",
        createdAt,
      },
    ],
    groups: [
      {
        id: "g_a2607",
        name: "A2607 FlowLink 项目组",
        avatar: avatar("流", "#07c160"),
        ownerId: "u_shenyan",
        memberIds: users.map((user) => user.id),
        admins: ["u_shenyan", "u_linche"],
        notice: "今日重点：完善资料页、群聊管理、文件消息和禁言能力。",
        description: "课程设计项目组，集中讨论 FlowLink 的需求、架构、联调和验收。",
        muted: false,
        muteAll: false,
        mutedMembers: [],
        createdAt,
      },
      {
        id: "g_frontend",
        name: "前端体验联调",
        avatar: avatar("前", "#2563eb"),
        ownerId: "u_linche",
        memberIds: ["u_linche", "u_xuzhihang", "u_shenyan"],
        admins: ["u_linche"],
        notice: "重点检查消息气泡、未读、重连、输入反馈和文件卡片。",
        description: "前端 UI、WebSocket 客户端和交互体验联调小组。",
        muted: false,
        muteAll: false,
        mutedMembers: [],
        createdAt,
      },
    ],
    messages: [
      messageSeed("m_1", "group", "g_a2607", "u_shenyan", "今天先按文档跑通 MVP：账号、好友、私聊、群聊和 ACK。", -55),
      messageSeed("m_2", "group", "g_a2607", "u_linche", "UI 我会参考微信的三栏结构，聊天体验先做顺滑。", -48),
      messageSeed("m_3", "group", "g_a2607", "u_xuzhihang", "WebSocket 客户端会加重连、输入中状态和文件发送。", -42),
      messageSeed("m_4", "private", privateConversationId("u_linche", "u_shenyan"), "u_shenyan", "林澈，先把 demo 做到能演示实时聊天就很够用了。", -35),
      messageSeed("m_5", "private", privateConversationId("u_linche", "u_shenyan"), "u_linche", "收到，我会把未读、历史、图片和文件消息也一起带上。", -31),
      messageSeed("m_6", "private", privateConversationId("u_linche", "u_xuzhihang"), "u_xuzhihang", "状态机这块我建议按 conversationId 做统一索引。", -24),
      messageSeed("m_7", "group", "g_frontend", "u_linche", "这个页面先不做成营销页，打开就是聊天工作台。", -18),
    ],
    fileRecords: [],
    notifications: [],
    adminLogs: [],
  };
}
